spring:
  # 配置数据源信息
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root1234
        slave_1:
          url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root1234



  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    password: root1234
  #    username: root
  #    url: jdbc:mysql://localhost:3306/db1?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  #   type: com.zaxxer.hikari.HikariDataSource


  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    username: root
  #    password: test
  #  sql:
  #    init:
  #      schema-locations: classpath:db/schema-h2.sql
  #      data-locations: classpath:db/data-h2.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 1800

  #  redis:
  #    host: localhost
  #    port: 6379
  redis:
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 200
        #最大空闲
        max-idle: 300
        #最小空闲
        min-idle: 10
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003,127.0.0.1:8004

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    #是否信任所有包(如果传递的是对象则需要设置为true，默认是传字符串)
    packages:
      trust-all: true
    #连接池
    pool:
      enabled: true
      max-connections: 5
      idle-timeout: 30000
  jms:
    pub-sub-domain: true
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: zk-discovery-client1

my-queue: queue1
sec-queue: queue3
topic1: topic1
topic2: topic2

my-service:
  ip: ni-hou
  port: 88888888
mybatis-plus:
  configuration:
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
server:
  port: 8081


